# Generated by Django 6.1.1 on 2026-10-07 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioBiblioteca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("identificacion", models.CharField(max_length=50, unique=True)),
                ("nombres", models.CharField(max_length=200)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                (
                    "rol",
                    models.CharField(
                        choices=[("estudiante", "Estudiante"), ("docente", "Docente")],
                        max_length=20,
                    ),
                ),
                ("carrera", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("bloqueado", "Bloqueado")],
                        default="activo",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=20, unique=True)),
                ("titulo", models.CharField(max_length=200)),
                ("editorial", models.CharField(max_length=100)),
                ("anio", models.IntegerField()),
                ("categoria", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("autores", models.ManyToManyField(to="gestion_biblioteca.autor")),
            ],
        ),
        migrations.CreateModel(
            name="Ejemplar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_barras", models.CharField(max_length=50, unique=True)),
                ("ubicacion", models.CharField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("prestado", "Prestado"),
                            ("perdido", "Perdido"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_biblioteca.libro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prestamo", models.DateField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateField()),
                ("devuelto", models.BooleanField(default=False)),
                (
                    "multa",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Ej: dañado, páginas faltantes", null=True
                    ),
                ),
                (
                    "ejemplar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_biblioteca.ejemplar",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_biblioteca.usuariobiblioteca",
                    ),
                ),
            ],
        ),
    ]
